CREATE DATABASE pizzadb;

USE pizzadb;

SELECT * FROM pizza_sales LIMIT 5;

-- 1. TOTAL REVENUE
SELECT SUM(TOTAL_PRICE)  AS TOTAL_REVENUE FROM PIZZA_SALES;

-- 2. AVERAGE ORDER VALUE 
SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES;
SELECT COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;
SELECT SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID) AS AVG_ORDER_VALUE FROM PIZZA_SALES;

-- 3. TOTAL PIZZAS SOLD
SELECT SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD FROM PIZZA_SALES;

-- 4. TOTAL ORDERS
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES;

-- 5. AVERAGE PIZZA PER ORDER
SELECT CAST(SUM(QUANTITY)/COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS AVG_PIZZA_PER_ORDER FROM PIZZA_SALES;







